Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 4, in <module>
    prnt("Ingrese 270 numeros: ")
NameError: name 'prnt' is not defined
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
12
124
4531
121321
123131
1234
1543
12314
15341
15341
12324
1212324
12324
1234
12324
123242
212455324
1
0
412
00
124
0
11244
0545
10
12
0
20540
4401
15240
14
01
204
4
54
4
456
4

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
0242
24520
054
5045
0455
54242402
45254
02
540
2
452
42
54
054
24
52
42
45
240

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
05
>>> 
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
7521
210
05
0570
05
72
7040
0427
0
052
2
07
0
74
07412
072
042
0
0
0742
042
0705

Traceback (most recent call last):7
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
705
04
5
24
045
24
2204
524502
424
504
524254
20452
45245
245
2452
40452
04
2545420
20
02
45278
2
00
02
245
045
40
40245
0452
40244520
070
0
07522
45045
228760
742
4204
2872
24
0452
075
04
2754
475
8
51
407
5
21
054
24
527
8
50

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
2
>>> 5445
5445
2
>>> 2
2
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
542
123254
121
1240
450
41210
5106
012
1213
154
0
0
0
0
0
0

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
0
0

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
0
>>> 
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
15453
545
4154
4154
1544
123
12321
4563
1234
5361
1232123
543553
23524
24
4563
4563
4123
1234
4563
2368
68
48
46
474
144
4563
12354
456
156
156
15
454
4
5
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
45245
452
54
4
54
5

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
5
>>> 
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
45
78
05
0
4556
456
12
121
121
020
015
0
02123
0
151
021
021
153.
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 6, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: '153.'
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
456
45
45
4542
12345
40
40
400
000
64542
451564
6678
4634
21234
4534
45321
45321
456453
43
535637
3563573
735473
56345
6709
689098
967
8076
89
768
086980
76896780
7689
86780
670
0
6879
68
0
67
60
6
89
678967
690
6896
69768
0768
0
60
60
0
6896789
0
696
0
6896
06
6
6
6
9868
0
6
8
68967
0
6896
0
6897689
0
66896
0
6789678
9
689
0
80
0
896789
0
689
0
6896789
0
678967
8096
6896
68965
6890
768960
6879
0
67895
8758
9768
0
6896
0
69
98
68
0
8796
0
986
0
9867
0
68976
986
897
68789
0
67896
0
6896
0
6896
76890
0
0
0
68968
9678996
9678
0
6789
076
967896
0
0
6789
0
6896
0
6890
0
0
6896
0
0
0
86789
0
6890
0
67896
0
689
0
98678
0
68
87
696
578
578
9
57
89
0
985
9
89
0
0
6789
06
6789
06
06
8
68960
6896809
689
68
696
6
0
8967
0
6896
0
68796
0
6896
0
0
0
0
0
786
5
57
785
9
58
9689
60
68896
987
444
455
4563
454
5
45
54
545
3
45
425
78960
689
0
06879
67895
980
0
689
0
6875
0
689
0
6896
06
6896
06
9867
0678
6896
69687
986
0876
689
0
0
689
06069
68
96867
09
67
97
679
89
0
98
09
876
986
0
0
9876
0
689
696996
6876
67
7
7
7
7976
987
6878
453
45153
2454
21213
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 13, in <module>
    PP=SP/CP
ZeroDivisionError: division by zero
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
156
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 13, in <module>
    CI+=1
NameError: name 'CI' is not defined
>>> 
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
15
123
121
3
12
31
21
3
12
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 15, in <module>
    PP=SP/CP
ZeroDivisionError: division by zero
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
45
545
45
35
2
424
5
43
54
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 15, in <module>
    PP=SP/CP
ZeroDivisionError: division by zero
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
45
35
45
4
5654
4
5
5
6354
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 16, in <module>
    print(f("La cantidad de numeros impares ingresados es de {CI} y la suma d ellos es de {SI}"))
NameError: name 'f' is not defined
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
213
123
210
0
21
2
54
10
24
La cantidad de numeros impares ingresados es de 3 y la suma d ellos es de 357
El cantidad de numeros pares ingresados es de 5 y su promedio es de60.0
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
1
1
1
1
1
1
1
1
1
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 15, in <module>
    PP=SP/CP
ZeroDivisionError: division by zero
1
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 

 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
1
1
1
1
1
1
1
1
1
La cantidad de numeros impares ingresados es de 4 y la suma d ellos es de 4
Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 18, in <module>
    print(f"El cantidad de numeros pares ingresados es de {CP} y su promedio es de{PP}")
NameError: name 'PP' is not defined
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 

 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 

Traceback (most recent call last):
  File "C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py", line 7, in <module>
    N=int(input(""))
ValueError: invalid literal for int() with base 10: ''
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
 
>>> 
Ingrese 270 numeros: 
1
1
11
1
La cantidad de numeros impares ingresados es de 4 y la suma d ellos es de 14
El cantidad de numeros pares ingresados es de 0 y su promedio es de0
>>> 
 RESTART: C:\Users\roberto.rosaesc-PC\Documents\escuela\Ico\1_semestre\programacion\CYPRobertoQE\libro\problemasresueltos\capitulo3\problema3_1.py.py 
Ingrese 270 numeros: 
2
2
2
2
La cantidad de numeros impares ingresados es de 0 y la suma d ellos es de 0
La cantidad de numeros pares ingresados es de 4 y su promedio es de2.0
2
>>> 
